### Create
POST http://127.0.0.1:3030/api/v1/boards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImplZmZAZXhhbXBsZS5jb20iLCJleHAiOjE3Njk1NzcyNDAsInB1Yl9pZCI6IjA2ZTQwY2IyLTQ2ZDEtNGFhZi1hZTBlLWMxMjdmYzg0ZjcwOCIsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6N30.TA0eEudUPh5ZW5GYhwgQ-KqM5vmw9yfZscTMcaImwgk
Content-Type: application/json

{
    "title": "Testing add board 2",
    "description": "description for testing add board",
    "due_date": "2026-01-30T08:00:00+07:00"
}

### Update
PUT http://127.0.0.1:3030/api/v1/boards/62c9c499-1a36-487a-808a-56a3d9b3f0f7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImplZmZAZXhhbXBsZS5jb20iLCJleHAiOjE3Njk1NzcyNDAsInB1Yl9pZCI6IjA2ZTQwY2IyLTQ2ZDEtNGFhZi1hZTBlLWMxMjdmYzg0ZjcwOCIsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6N30.TA0eEudUPh5ZW5GYhwgQ-KqM5vmw9yfZscTMcaImwgk
Content-Type: application/json

{
    "title": "Project Alpha Updated lagii",
    "description": "Updated 2 project board description",
    "due_date": "2026-02-15T08:00:00+07:00"
}


### Add Members
POST http://127.0.0.1:3030/api/v1/boards/62c9c499-1a36-487a-808a-56a3d9b3f0f7/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImplZmZAZXhhbXBsZS5jb20iLCJleHAiOjE3Njk1MjgyMzAsInB1Yl9pZCI6IjA2ZTQwY2IyLTQ2ZDEtNGFhZi1hZTBlLWMxMjdmYzg0ZjcwOCIsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6N30.1URYjhI3NFUVXEtUsPJU2QHEjdVor-ecfy-PYXowp4Y
Content-Type: application/json

[
    "06e40cb2-46d1-4aaf-ae0e-c127fc84f708",
    "d1fc3154-3e6a-412b-9796-387508a8f5c4"
]

### Remove Members
DELETE http://127.0.0.1:3030/api/v1/boards/62c9c499-1a36-487a-808a-56a3d9b3f0f7/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImplZmZAZXhhbXBsZS5jb20iLCJleHAiOjE3Njk1MzI0NDIsInB1Yl9pZCI6IjA2ZTQwY2IyLTQ2ZDEtNGFhZi1hZTBlLWMxMjdmYzg0ZjcwOCIsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6N30.rxYKU68qqfMPSW7Viey-53NwV-9BJ8ENxajbpT5ZdkE
Content-Type: application/json

[
    "06e40cb2-46d1-4aaf-ae0e-c127fc84f708"
]

### Get My Boards Paginated
GET http://127.0.0.1:3030/api/v1/boards/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlbnRlbkBleGFtcGxlLmNvbSIsImV4cCI6MTc2OTY5MjUzNSwicHViX2lkIjoiZDFmYzMxNTQtM2U2YS00MTJiLTk3OTYtMzg3NTA4YThmNWM0Iiwicm9sZSI6InVzZXIiLCJ1c2VyX2lkIjo2fQ.2wiuUTJyvtyiv3Me2WEcnx3MGrX8UBGo3_12dFkrOoc

### GET LISTS ON BOARD
GET http://127.0.0.1:3030/api/v1/boards/62c9c499-1a36-487a-808a-56a3d9b3f0f7/lists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlbnRlbkBleGFtcGxlLmNvbSIsImV4cCI6MTc3MDEzNTQxMywicHViX2lkIjoiZDFmYzMxNTQtM2U2YS00MTJiLTk3OTYtMzg3NTA4YThmNWM0Iiwicm9sZSI6InVzZXIiLCJ1c2VyX2lkIjo2fQ.LnpyayFXOvjk8iYPVwO0xDPW-pc3V-Qj3GbbygGbHYI